### PR TITLE
1136 layout issue

### PR DESCRIPTION
**Pull request by ravitoait**
Added margin top and bottom

### CODE REVIEW

**Comment by k8vance88** [comment]
I pulled the commit and it is better, but it still has a problem:
image

**Comment by ravitoait** [comment]
image

I guess changed spacing looks more promising.

**Comment by k8vance88** [comment]
Still I think for longer namespaces, we would still have the problem.  Instead look at making the dropdown wider and allow wrap.  You may still want to add margin.

**Comment by k8vance88** [comment]
Here's the new look:
image

**Comment by k8vance88** [comment]
Fixes https://github.ibm.com/IBMCloudPak4Apps/appnav-roadmap/issues/1136

**Pull request merged**
